name: dimagh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  flutter_slidable: ^4.0.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true